name: CD

on:
  push:
    branches:
      - release

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install all dependencies
      run: |
        yarn install
        yarn global add aurelia-cli
    - name: Build
      run: |
        au test
        yarn run analyze
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install production dependencies
      run: |
        yarn install --production=true
    - name: Build
      run: |
        yarn run build
    - name: Upload to S3
      run: |
        aws s3 sync ./dist s3://proximo-web-blue
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.CD_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.CD_AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-west-2'

