name: CD

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install production dependencies
      run: |
        yarn
    - name: Build
      run: |
        yarn run test
        yarn run build
    - name: Upload to S3
      run: |
        aws s3 sync ./dist s3://proximo-web-prod/production
        aws cloudfront create-invalidation --distribution-id E37E94QEJZM9N6 --invalidation-batch "Paths={Quantity=1,Items=[/*]},CallerReference=$GITHUB_SHA"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.CD_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.CD_AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-west-2'

